---
title: "Exercise 3"
author: "Nick Head"
date: "11 March 2015"
output: html_document
---

###Q1 Generating normal random variables

####a: Using central limit theorem

```{r}
SimNormalCLT <- function (Nsims) {
  Nvec = numeric(Nsims)
  i = 0
  while(i < Nsims){
    N = sum(runif(12)) - 6
    Nvec[i] = N
    i = i + 1
  }
}
```

####b: Using Box Muller

```{r}
SimNormalBoxMuller <- function (Nsims) {
  i = 0
  Nvec = numeric(Nsims)
  while(i < Nsims){
    u1 = runif(1)
    u2 = runif(1)
    r = sqrt(-2 * log(u1))
    theta = 2 * pi * u2
    x = r * cos(theta)
    y = r * sin(theta)
    Nvec[i] = x
    Nvec[i+1] = y
    i = i + 2
  }
}
```

####c: Using Polar-Mascaglia
```{r}
SimNormalPolar <- function (Nsims) {
  i = 0
  Nvec = numeric(Nsims)
  while(i < Nsims){
    u1 = runif(1)
    u2 = runif(1)
    v1 = (2*u1)-1
    v2 = (2*u2)-1
    S = v1^2 + v2^2
    if(S < 1){ # inside the unit circle
      i = i + 2
      foo = sqrt((-2 * log(S))/S)
      x = foo * v1
      y = foo * v2
      Nvec[i] = x
      Nvec[i+1] = y
    }
  }
}
```

####d: Using Ratio of Uniforms

```{r}
SimNormalRatioUniforms <- function (Nsims) {
  i = 0
  Nvec = numeric(Nsims)
  while(i < Nsims){
    u = runif(1, 0, 1)
    v = runif(1, -1, 1)
    if(v^2 < -4 * u^2 * log(u)){ # test
      i = i + 1
      Nvec[i] = v/u
    }
  }
}
```

####e: Using `rnorm`

```{r}
Nsims = 50000
Nvec = rnorm(Nsims)
```

####f: Benchmarking

```{r}
library(microbenchmark)
microbenchmark(SimNormalCLT(Nsims), 
               SimNormalRatioUniforms(Nsims),
               SimNormalBoxMuller(Nsims),
               SimNormalPolar(Nsims),
               rnorm(Nsims),
               times = 1
)
```

###2

####a: Using Accept-Reject

```{r}
alpha <- 8
beta <- 6
```

```{r}
library(devtools)
source_gist("https://gist.github.com/headsphere/c49eeb3921c56efb537c")

SimBetaAcceptReject <- function (alpha, beta, Nsim, plot = FALSE) {
  successCount = SimulateAcceptReject(Nsim, 
                                      f_fn = function (x){dbeta(x,alpha,beta)},
                                      g_fn = function (y) {dunif(y)},
                                      randg_fn = function (Nsim) {runif(Nsim)},
                                      plot = plot)
}

SimBetaAcceptReject(alpha, beta, 1000, TRUE)


```

####b: Using sum of gammas

```{r}
i = 0 
Nvec = numeric(Nsims)
while(i < Nsims){
  i = i + 1
  g1 = rgamma(1, alpha, 1)
  g2 = rgamma(1, beta, 1)
  Nvec[i] = g1 + g2
}
hist(Nvec)
ks.test(Nvec, "dbeta", alpha, beta)
```

###3

####a: Using exponential interarrival times
```{r}
Nsims = 100
lambda = 16
y = rep(0, Nsims)
e1 = exp(-lambda)
z = runif(Nsims)
for(i in 1:Nsims){
  k = 0
  u = z[i]
  while(u > e1){
    u = u * runif(1)
    k = k + 1
  }
  y[i] = k
}
hist(y)
mean(y)
```

####b: Using table lookup

```{r}
t=seq(0,2*lambda)
prob=ppois(t, lambda)
xTable=numeric(Nsims)
uvec = runif(Nsims)
xTable = as.numeric(lapply(uvec, function(u){ sum(prob<u)}))
hist(xTable)
mean(xTable)
```

###4
$$\int_0^2{x^x dx}$$

Using crude estimation:
```{r}
u = runif(1000, 0, 2)
mean(u^u)*(2-0)
```
Using hit-or-miss (THIS IS NOT WORKING PROPERLY!):
```{r}
HitOrMiss <- function () {
  n = 10000
  t = 0
  x = 0
  while(t < n){
    u = runif(1, 0, 2)
    y = runif(1, 0, 2)
    #up = 1/(1 + u**3)
    up = u^u
    if(y < up){
      x[t] = 1
    }
    else{
      x[t] = 0
    }
    t = t + 1
  }
  total = sum(x)
  return(total/n)
}
res = 0
for(i in 1:10){
  res = res + HitOrMiss()
}
res/10
```

